INSERT INTO rating (rating_name) values ('G')
INSERT INTO rating (rating_name) values ('PG')
INSERT INTO rating (rating_name) values ('PG13')
INSERT INTO rating (rating_name) values ('R')
INSERT INTO rating (rating_name) values ('NC17')
INSERT INTO genres (name) values ('Драма')
INSERT INTO genres (name) values ('Комедия')
INSERT INTO genres (name) values ('Художественный фильм')
INSERT INTO genres (name) values ('Короткометражка')
INSERT INTO genres (name) values ('Боевик')
INSERT INTO genres (name) values ('Приключеченский фильм')
INSERT INTO genres (name) values ('Криминал')
INSERT INTO genres (name) values ('Фильмы ужасов')
INSERT INTO genres (name) values ('Фэнтези')
INSERT INTO genres (name) values ('Романтика')
INSERT INTO genres (name) values ('Триллер')
INSERT INTO genres (name) values ('Анимация')
INSERT INTO genres (name) values ('Семейный')
INSERT INTO genres (name) values ('Военный')
INSERT INTO genres (name) values ('Документальный')
INSERT INTO genres (name) values ('Мюзикл')
INSERT INTO genres (name) values ('Биографический')
INSERT INTO genres (name) values ('Научная фантастика')
INSERT INTO genres (name) values ('Вестерн')
INSERT INTO genres (name) values ('Пост-апокалипсис')